apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.example.martin-helmich.de
spec:
  group: example.martin-helmich.de
  scope: Namespaced
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            required: 
            - replicas
            properties:
              replicas:
                type: integer
                minimum: 1
            type: object
        type: object
    served: true
    storage: true
